---
- name: Install and configure Nginx on the web server
  hosts: localhost
  gather_facts: yes
  become: yes  # Ensure we have root privileges

  vars_prompt:
    - name: "website_number"
      prompt: "Enter the website number (1, 2, ...)"
      private: no
    - name: "git_repo"
      prompt: "Enter the Git repository URL to clone the website"
      private: no
    - name: "subdir"
      prompt: "Enter a subdirectory for the website if the Git project has one"
      private: no
    - name: "server_name"
      prompt: "Enter the server name (e.g., neta1.example.com)"
      private: no

  tasks:
    - name: Install Nginx and Git
      ansible.builtin.apt:
        name:
          - nginx
          - git
        state: present
        update_cache: yes

    - name: Allow Nginx through the firewall
      ansible.builtin.ufw:
        rule: allow
        name: 'Nginx HTTP'

    - name: Ensure /var/www/website directory exists with correct ownership
      ansible.builtin.file:
        path: "/var/www/website{{ website_number }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Mark the directory as safe for Git (to avoid dubious ownership error)
      ansible.builtin.command:
        cmd: "git config --global --add safe.directory /var/www/website{{ website_number }}"

    - name: Clone the website from Git
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "/var/www/website{{ website_number }}"
        update: yes  # Ensures it pulls the latest changes if the directory exists
        force: yes
        ignore_errors: yes

    - name: Set ownership of the website files
      ansible.builtin.file:
        path: "/var/www/website{{ website_number }}"
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Configure Nginx for the website
      ansible.builtin.template:
        src: nginx_site.j2
        dest: "/etc/nginx/sites-available/website{{ website_number }}.conf"
        mode: '0644'

    - name: Enable the website configuration
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/website{{ website_number }}.conf"
        dest: "/etc/nginx/sites-enabled/website{{ website_number }}.conf"
        state: link

    - name: Add entry to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 {{ server_name }}"
        state: present

    - name: Test Nginx configuration
      ansible.builtin.command: nginx -t

    - name: Reload Nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded

