---
- name: Setup BIND9 DNS Server with Forward and Reverse Zone for Nameserver Only
  hosts: localhost
  become: yes
  gather_facts: yes

  vars_prompt:
    - name: "domain"
      prompt: "Enter the domain name (e.g., example.com)"
      private: no
    - name: "forwarder1"
      prompt: "Enter the first forwarder IP (e.g., 8.8.8.8)"
      private: no
    - name: "forwarder2"
      prompt: "Enter the second forwarder IP (leave blank if none)"
      private: no
    - name: "internal_network"
      prompt: "Enter the internal network (e.g., 192.168.5.0/24)"
      private: no
    - name: "nameserver_ip"
      prompt: "Enter the IP address of the nameserver"
      private: no
    - name: "reverse_zone"
      prompt: "Enter the reverse zone network (e.g., 192.168.5 for 192.168.5.x addresses)"
      private: no

  tasks:
    - name: Install BIND9
      ansible.builtin.apt:
        name: bind9
        state: present
        update_cache: yes

    - name: Convert reverse zone IP for file naming
      set_fact:
        reverse_zone_file_name: "{{ reverse_zone.split('.') | reverse | join('.') }}"

    - name: Configure named.conf.local for the domain and reverse zone
      ansible.builtin.template:
        src: "./templates/named.conf.local.j2"
        dest: "/etc/bind/named.conf.local"
        mode: '0644'
      become: yes

    - name: Configure named.conf.options for forwarders and internal network
      ansible.builtin.template:
        src: "./templates/named.conf.options.j2"
        dest: "/etc/bind/named.conf.options"
        mode: '0644'
      become: yes

    - name: Create the forward DNS zone file for the domain (nameserver only)
      ansible.builtin.template:
        src: "./templates/db.domain.j2"
        dest: "/etc/bind/db.{{ domain }}"
        mode: '0644'
      become: yes

    - name: Create the reverse DNS zone file (PTR record for the nameserver)
      ansible.builtin.template:
        src: "./templates/db.reverse.j2"
        dest: "/etc/bind/db.{{ reverse_zone_file_name }}"
        mode: '0644'
      become: yes

    - name: Restart BIND9 service
      ansible.builtin.systemd:
        name: bind9
        state: restarted
        enabled: yes

    - name: Verify BIND9 configuration
      ansible.builtin.command: named-checkconf
      become: yes

    - name: Verify DNS zone file
      ansible.builtin.command: named-checkzone {{ domain }} /etc/bind/db.{{ domain }}
      become: yes

    - name: Verify reverse DNS zone file
      ansible.builtin.command: named-checkzone {{ reverse_zone_file_name }}.in-addr.arpa /etc/bind/db.{{ reverse_zone_file_name }}
      become: yes

