#!/bin/bash

### Flush existing rules ###
iptables -F
iptables -t nat -F
iptables -t mangle -F
iptables -X
iptables -t nat -F PREROUTING
iptables -t nat -F POSTROUTING

### Default policies: Drop everything by default, except allowed traffic ###
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP

### Allow DHCP server to only respond to DHCP requests ###
# Assuming DHCP server at 192.168.5.10
# Allow DHCP server to listen on port 67 and respond on port 68 (UDP)
iptables -A FORWARD -s 192.168.5.10 -p udp --sport 67 --dport 68 -j ACCEPT
iptables -A FORWARD -d 192.168.5.10 -p udp --sport 68 --dport 67 -j ACCEPT

### Allow MAIL server to only handle MAIL requests ###
# Assuming MAIL server at 192.168.5.20
# Allow SMTP (port 25) and IMAP (port 143) traffic for MAIL server
iptables -A FORWARD -s 192.168.5.20 -p tcp --sport 25 -j ACCEPT
iptables -A FORWARD -s 192.168.5.20 -p tcp --sport 143 -j ACCEPT
iptables -A FORWARD -d 192.168.5.20 -p tcp --dport 25 -j ACCEPT
iptables -A FORWARD -d 192.168.5.20 -p tcp --dport 143 -j ACCEPT

### Restrict internal Client workstations to only HTTP connections to the Internet ###
# Allow outgoing HTTP (port 80) traffic from client workstations to the Internet
iptables -A FORWARD -s 192.168.5.0/24 -p tcp --dport 80 -j ACCEPT
iptables -A FORWARD -d 192.168.5.0/24 -p tcp --sport 80 -j ACCEPT
# NAT rule to allow HTTP traffic from internal network to be routed to the Internet
iptables -t nat -A POSTROUTING -s 192.168.5.0/24 -o ens18 -j MASQUERADE

### Allow established and related connections ###
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT 

### Allow traffic on the loopback interface ###
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
